#!/usr/bin/perl
# This example shows how to output multiple samples to multiple files
# Notice how sources, files etc are all plural and refer to arrays

my $seq1 = new PostScript::Graph::Sequence;
$seq1->setup('color', [
    [0.5,0,0], [1,0,0], [1,1,0], [0.5,0.5,0], [0,1,0],
    [0,0.5,0], [0,0.5,0.5], [0,0,1], [0.5,0,0.5]
]);
$seq1->auto(qw(color));

my $bgnd_colour = [1, 0.95,0.95];

### Styles
my $fn_style = {
    sequence => $seq1,
    line => {
	width => 1.5,
	outer_color => 0.4,
    },
};

my $test_style = {
    sequence => $seq1,
    same => 1,
    line => {
	width => 3,
	dashes => [ 1, 2 ],
    },
};

### Model
verbose => 2,

source => {
    user     => 'test',
    password => 'test',
    database => 'test',
    mode     => 'offline',
    #mode     => 'fetch',
},

file => {
    landscape => 0,
},

charts => [
    default => {
	png => 1,
	dots_per_inch => 75,
	background => $bgnd_colour,
	invert => 1,
	x_axis => {
	    show_lines => 0,
	    mid_width  => 0,
	    mid_color  => $bgnd_colour,
	},
	key => {
	    background => $bgnd_colour,
	},
	prices => {
	    percent => 60,
	    points => {
		shape => 'candle2',
		inner_color => [1, 0.8, 0],
		outer_color => [0.4, 0.4, 0],
		width => 1,
	    },
	},
	volumes => {
	    percent => 40,
	    bars => {
		color => [0.6, 0.6, 0.2],
		width => 1,
	    },
	},
    },
],

sample => {
    dates_by   => 'weekdays',
    start_date => '2003-05-01',
    #end_date   => '2003-05-28'
},

