#!/usr/bin/perl
# version 0.01
use warnings;
use strict;
use DBIx::Namespace 0.03;

die "Usage: $0 <table_name>\n" unless $ARGV[0];
my $database = 'test';
my $table = shift;

my $db = new DBIx::Namespace(
	user     => 'test',
	password => 'test',
	database => 'test',
    );

my $r1;
eval {
    $r1 = $db->delete($table);
};
if ($@) {
    print "Deleting '$table' failed : $@\n";
} else {
    print "Deleting '$table' ", $r1 ? "succeeded\n" : "failed\n";
}
